#!/usr/bin/env bash
#
# Requires:
# - kubectl

set -eo pipefail

test -z "${1}" && echo "deployment selector required." 1>&2 && exit 1

selector="$1"

kubectl patch deployment $1 -p '{"spec":{"template":{"spec":{"containers":[{"name":"mycontainer","env":[{"name":"RESTART_","value":"'$(date +%s)'"}]}]}}}}'

